version: '3.9'
services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/data/db
    networks:
      - mjunction
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mjunction
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    container_name: server
    networks:
      - mjunction
    environment:
      - POSTGRES_DB=mjunction
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PORT=5050
    depends_on:
      - db

networks:
  data: {}
  mjunction:
    
